# Reference: https://qiita.com/tommy_aka_jps/items/65193185b520a1e2be21
name: Prevent workflow from being disabled

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  push-empty-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up git
        run: |
          # pullしておかないと Re-run all jobs 実行時はコケてしまうため
          git pull
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit and push
        run: |
          git commit --allow-empty -m "chore: Prevent workflow from being disabled automatically"
          git push
